### PR TITLE
Add support for SumsUp style Msg

### PR DESCRIPTION
**Pull request by hojberg**
Update Msg typing to support SumsUp sum types and clean up the example
apps to include classic and sums up examples

SumsUp sum types which can implement Msgs have a more closed definition that "something with a tag", so we're pulling it in directly to support it here. One downside is we loose some of the logging power of nested msgs, but that could likely be solved inside of sums-up's `toString` method.

### CODE REVIEW

**Comment by hojberg** [comment]
@newyankeecodeshop I'm gonna do this as a prerelease. Definitely speak up if you think this has unforeseen impact on the usage at Upserve. Additionally, would be nice to get your subscription work into the next version also.

**Comment by hojberg** [comment]
The main difference here is a deprecation of `tag` on msg's in favor of `type`, but both will be supported for some time.

**Comment by newyankeecodeshop** [comment]
@hojberg Why is this format deprecated? What does "FSA" stand for?
We've actually been moving away from the SumType message style at Upserve and sticking with switch statements. The TypeScript 3.4 `const` qualifier makes declaring messages rather concise:
```
function MyMessage(arg1: number) {
  return { tag: "MyMessage", arg1 } as const;
}
type MyMesage = ReturnType<typeof MyMessage>;
```

**Comment by hojberg** [comment]
FSA is Flux Standard Action. The idea was to align a little more with a pseudo standard. Your example will continue to work for the foreseeable future. The main difference with FSA is that `tag` is now `type` and that any data is nested under a `payload` field. SumsUp and it's more formal sum type approach conforms to an object with `type`.

Long winded way of saying that Gongfu still have no knowledge of SumsUp directly, and there's no intention to make that a requirement, though I did use it in the updated example.

FSA: https://github.com/redux-utilities/flux-standard-action

**Comment by hojberg** [comment]
Idk, perhaps it's silly to try and align with this standard.

**Comment by newyankeecodeshop** [comment]
@hojberg Interesting - I had never heard of FSA. I think adding support for that makes sense if it looks like it's getting traction. It might make Gongfu apps integrate well with debugging tools that are built for Redux for example.
FYI, the "error" type should be `error?: true` since the only defined value that is accepted is `true`.

**Comment by newyankeecodeshop** [comment]
And maybe Gongfu could use `meta` as a place to put the message path for logging.

**Comment by hojberg** [comment]
@newyankeecodeshop yeah thats a cool idea!

**Pull request merged**
